[project]
name = "edualg"
version = "0.0.3"
description = "Educational implementations of data structures and algorithms"
authors = [
  { name="Maxim Bobkow" }
]
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"